
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace asc_general.Models
{

using System;
    using System.Collections.Generic;
    
public partial class health_staff
{

    public int id { get; set; }

    public string name { get; set; }

    public string profession { get; set; }

    public string photo { get; set; }

    public string text_about { get; set; }

    public string instagram { get; set; }

    public string facebook { get; set; }

    public string phone { get; set; }

    public string email { get; set; }

}

}
